Add ability to pass custom HTTP headers to Anthropic client
run-llama/llama_index pull request #12506
Opened 2024-04-02 23:27 UTC by ashishb

Add the ability to pass custom HTTP headers to Anthropic client

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [ ] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

2024-04-03 04:50 UTC, nerdai requested changes

2024-04-03 04:50 UTC, nerdai commented on llama-index-legacy/llama_index/legacy/llms/anthropic.py
We shouldn't really be updating legacy (llama-index v0.9.42).

Can we please update llama-index-llms-anthropic instead?

2024-04-03 20:19 UTC, ashishb commented on llama-index-legacy/llama_index/legacy/llms/anthropic.py
@nerdai sounds good
https://github.com/run-llama/llama_index/pull/12558/

2024-04-04 01:48 UTC, logan-markewich commented
Closing in favour of https://github.com/run-llama/llama_index/pull/12558

2024-04-04 01:48 UTC, closed without merging