Fix kuzu integration .execute() calls, which require a dict not a list of tuples
run-llama/llama_index pull request #13100
Opened 2024-04-25 08:10 UTC by ZmeiGorynych

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes https://github.com/run-llama/llama_index/issues/9244

## New Package? N/A

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [ ] Yes
- [ ] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [x ] No

## Type of Change

Please delete options that are not relevant.

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Ran the [Kuzu example](https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/index_structs/knowledge_graph/KuzuGraphDemo.ipynb), it was broken before my changes and now it runs fine both on Mac and Windows.
- [ ] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

2024-04-25 16:53 UTC, nerdai commented
Thanks @ZmeiGorynych, can you also please update the version (patch) number in `pyproject.toml`?

2024-04-25 17:00 UTC, nerdai commented
@ZmeiGorynych looks like lint/fmt checks are failing can you please run:

`make lint` and `make format`

2024-04-26 05:41 UTC, nerdai requested changes

2024-04-26 05:41 UTC, nerdai commented on pyproject.toml
Hey sorry not this pyrpoject.toml but the one found in the llama-index-graph-stores-kuzu. Please revert this one and modify the one mentioned in previous sentence :)

2024-04-26 12:05 UTC, ZmeiGorynych commented on pyproject.toml
Done

2024-04-26 12:24 UTC, nerdai approved these changes
Lgtm!

2024-04-26 15:45 UTC, merged