gpt-4o support
run-llama/llama_index pull request #13463
Opened 2024-05-13 17:38 UTC by logan-markewich

2024-05-13 17:41 UTC, nerdai approved these changes

2024-05-13 17:50 UTC, himself65 requested changes

2024-05-13 17:50 UTC, himself65 commented on llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
> +    "gpt-4o": 128000,
gpt-4o-2024-05-13

2024-05-13 17:54 UTC, merged

2024-05-14 15:06 UTC, Prem95 commented on llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py
> +    "gpt-4o": 128000,
Isn't it the same?