Azure AI Inference integration
run-llama/llama_index pull request #14672
Opened 2024-07-09 23:15 UTC by santiagxf

# Description

This PR introduces two new packages to the LlamaIndex ecosystem, bringing support for models deploy to Azure AI studio and Azure Machine Learning either with models-as-a-service (serverless API endpoints) or managed infrastructure (managed online endpoints).

Packages introduced:

* `llama-index-llms-azure-inference`
* `llama-index-embeddings-azure-inference`

Fixes # (issue)

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [x] Yes
- [ ] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [x] No

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added new unit/integration tests
- [ ] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added Google Colab support for the newly added notebooks.
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

2024-07-10 01:23 UTC, dargilco requested changes

2024-07-10 01:32 UTC, johanste requested changes

2024-07-10 01:32 UTC, johanste commented on llama-index-integrations/embeddings/llama-index-embeddings-azure-inference/llama_index/embeddings/azure_inference/base.py
> +        self._async_client = EmbeddingsClientAsync(
Async clients with sync token credentials are problematic (it will make sync/blocking calls...)

2024-07-15 21:59 UTC, dargilco approved these changes

2024-07-19 15:22 UTC, logan-markewich approved these changes
LGTM me, thanks for adding :)

2024-07-19 15:22 UTC, merged