feat(integration): add a global handler for Literal AI
run-llama/llama_index pull request #15064
Opened 2024-07-31 15:11 UTC by Dam-Buty

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## New Package?

Did I fill in the `tool.llamahub` section in the `pyproject.toml` and provide a detailed README.md for my new integration or package?

- [x] Yes
- [ ] No

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [x] Yes
- [ ] No

## Type of Change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## How Has This Been Tested?

I added an example script and hacked at it until it worked :thinking: 

- [x] I stared at the code and made sure it makes sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

2024-07-31 15:34 UTC, desaxce commented on llama-index-integrations/callbacks/llama-index-callbacks-literalai/README.md
> +# LlamaIndex Callbacks Integration: Literalai
Maybe put Literal AI

2024-08-01 07:06 UTC, masci requested changes
Thanks for the contribution! Do you mind filling the PR description explaining what the change is to help me review this? TIA!

2024-08-02 14:10 UTC, masci requested changes
PR looks great, I've only found two almost invisible typos in the docs 😬

2024-08-02 14:10 UTC, masci commented on docs/docs/module_guides/observability/index.md
> +You can then navigate to **Settings**, grab your API key, and start logging !
```suggestion
You can then navigate to **Settings**, grab your API key, and start logging!
```

2024-08-02 14:10 UTC, masci commented on docs/docs/module_guides/observability/index.md
> +# You should provide your Literal AI API key and base url using the following environment variables :
```suggestion
# You should provide your Literal AI API key and base url using the following environment variables:
```

2024-08-05 08:53 UTC, Dam-Buty commented
Thanks for the keen eye @masci ! Both suggestions applied

2024-08-05 09:37 UTC, merged