feat: add default_headers to Gemini model
run-llama/llama_index pull request #15141
Opened 2024-08-04 09:51 UTC by ashishb

# Description

Similar to [OpenAI](https://github.com/run-llama/llama_index/blob/9900560183a2e212515e6273e63159316e056e96/llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py#L190-L192), allow `default_headers` for Gemini model as well

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] I stared at the code and made sure it made sense

## Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I ran `make format; make lint` to appease the lint gods

2024-08-04 21:08 UTC, ashishb commented
@logan-markewich can you please review?

2024-08-05 09:47 UTC, masci requested changes
Left a comment about documentation.

2024-08-05 09:47 UTC, masci commented on llama-index-integrations/llms/llama-index-llms-gemini/llama_index/llms/gemini/base.py
> +            config_params["default_metadata"] = default_metadata
I'm not a `genai` expert and it took me a while to figure out why something called `default_metadata` would end up becoming HTTP headers 😅 so I thought a comment would help here.

```suggestion
            # `default_metadata` contains (key, value) pairs that will be sent with every request.
            # When using `transport="rest"`, these will be sent as HTTP headers.
            config_params["default_metadata"] = default_metadata
```

2024-08-05 17:20 UTC, ashishb commented
> Left a comment about documentation.

Thanks. Accepted.

2024-08-06 09:15 UTC, masci approved these changes

2024-08-06 09:22 UTC, masci commented
Bumped the version so integration will be released on merge.

2024-08-06 09:36 UTC, merged