Check if hnsw index exists
run-llama/llama_index pull request #15287
Opened 2024-08-11 14:27 UTC by xevo

# Description

When using  `llama_index.vector_stores.postgres.PGVectorStore` to store embedding in PostgreSQL, the hnsw index gets created multiple times. This happens when passing in `hnsw_kwargs` to create a PGVectorStore() instance.

This PR updates the `_create_hnsw_index` method to check for the existence of the hnsw index before creating it. If it does exist, the index creation will be skipped.  

## Version Bump?

Did I bump the version in the `pyproject.toml` file of the package I am updating? (Except for the `llama-index-core` package)

- [ ] Yes
- [x] No

## Type of Change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] I stared at the code and made sure it makes sense

This is the simplest test script I could come up with: https://gist.github.com/xevo/310beb1aed656f081b5a30336d8f788d

## Suggested Checklist:

- [x] I have performed a self-review of my own code

2024-08-12 08:54 UTC, masci requested changes
Nice! Can you add a unit test to cover this change?

2024-08-12 22:01 UTC, xevo commented
> Nice! Can you add a unit test to cover this change?

Thank you :smile: I added a new test to make sure that only one index gets created after multiple PGVectorStore instances are initialized. I ran this locally and the test passes with the new change in the PR but fails without it (as expected).

2024-08-13 10:55 UTC, masci requested changes
Thanks for adding the test case! Change LGTM, can you bump the package version so we'll release on merge?

2024-08-13 14:10 UTC, xevo commented
> Thanks for adding the test case! Change LGTM, can you bump the package version so we'll release on merge?

@masci Cool, I bumped the version, did I do that right?: https://github.com/run-llama/llama_index/pull/15287/commits/41e0c336d8f53dbe8793daf2aa451e0ba81e0f00

2024-08-13 14:12 UTC, masci approved these changes
All good, waiting for the CI to go green, merge and release 🚀

2024-08-13 14:36 UTC, merged