chore: update JinaEmbedding for v3 release
run-llama/llama_index pull request #15971
Opened 2024-09-12 03:29 UTC by DresAaron

# Description

Modified the `JinaEmbedding` class to align with the up-coming model release of `jina-embeddings-v3`.

2024-09-12 06:43 UTC, JoanFM requested changes

2024-09-12 06:43 UTC, JoanFM commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +VALID_TASK_TYPE = ["retrieval.passage", "retrieval.query", "clustering", "classificatoin", "text-matching"]
no clustering, separation

2024-09-12 06:43 UTC, JoanFM requested changes
lets try not to mask json package

2024-09-12 06:43 UTC, JoanFM commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +            json = {
```suggestion
            input-json = {
```

2024-09-13 05:05 UTC, nan-wang commented
@JoanFM Will the users be able to select the `dimensions`?

2024-09-16 09:02 UTC, CatStark requested changes
Change name for the tasks

2024-09-16 09:02 UTC, CatStark commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +                input_json["task_type"] = task_type
```suggestion
                input_json["task"] = task
```

2024-09-16 09:02 UTC, CatStark commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +    _task_type: str = PrivateAttr()
```suggestion
    _task: str = PrivateAttr()
```

2024-09-16 09:02 UTC, CatStark commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +        task_type: Optional[str] = None,
```suggestion
        task: Optional[str] = None,
```

2024-09-16 09:02 UTC, CatStark commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +        self._task_type = task_type
```suggestion
        self._task = task
```

2024-09-16 09:02 UTC, CatStark commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +        if self._task_type:
```suggestion
        if self._task:
```

2024-09-16 09:02 UTC, CatStark commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +                self._task_type in VALID_TASK_TYPE
```suggestion
                self._task in VALID_TASK
```

2024-09-16 09:02 UTC, CatStark commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +            ), f"Task Type parameter {self._task_type} not supported. Please choose one of {VALID_TASK_TYPE}"
```suggestion
            ), f"Task Type parameter {self._task} not supported. Please choose one of {VALID_TASK}"
```

2024-09-16 09:02 UTC, CatStark commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +            task_type=self._task_type,
```suggestion
            task=self._task,
```

2024-09-16 09:02 UTC, CatStark commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +            task_type=self._task_type,
```suggestion
            task=self._task,
```

2024-09-16 09:02 UTC, CatStark commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +            task_type=self._task_type,
```suggestion
            task=self._task,
```

2024-09-16 09:02 UTC, CatStark commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +            task_type=self._task_type,
```suggestion
            task=self._task,
```

2024-09-17 08:06 UTC, nan-wang commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +        model (str): Model for embedding. When it is `jina-embeddings-v3`, `task_type` is required.
```suggestion
        model (str): Model for embedding. When it is `jina-embeddings-v3`, `task` is required.
```

2024-09-17 08:06 UTC, nan-wang requested changes
Minor issue

2024-09-18 07:13 UTC, JoanFM requested changes

2024-09-18 07:13 UTC, JoanFM commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +        model (str): Model for embedding. When it is `jina-embeddings-v3`, `task` is required.
this will not be true

2024-09-18 07:13 UTC, JoanFM commented on llama-index-integrations/embeddings/llama-index-embeddings-jinaai/llama_index/embeddings/jinaai/base.py
> +        if self._task:
actually you could just let the API return the error. So u do not need to mantain the logic here

2024-09-18 08:07 UTC, nan-wang approved these changes
LGTM

2024-09-18 08:47 UTC, DresAaron commented
@logan-markewich could you please take a look?

2024-09-18 17:32 UTC, logan-markewich approved these changes

2024-09-18 17:39 UTC, merged