Add Falkordb vectorstore Integration
run-llama/llama_index pull request #16047
Opened 2024-09-16 17:21 UTC by A5jadAli

This pull request introduces support for FalkorDB as a vectorstore option in LlamaIndex. The changes include:

- Integration code: Added new code in base.py to handle operations with Falkordb following the structure of other vectorstore integrations.
- Testing: Included tests.py to verify the integration works as expected.

2024-09-19 07:44 UTC, AviAvni requested changes
it look like more tests need to be added

2024-09-19 07:44 UTC, AviAvni commented on llama-index-integrations/vector_stores/llama-index-vector-stores-falkordb/llamaindex/falkordbvector/base.py
> +def check_if_not_null(props: List[str], values: List[Any]) -> None:
this function only used once just inline it

2024-09-19 07:44 UTC, AviAvni commented on llama-index-integrations/vector_stores/llama-index-vector-stores-falkordb/llamaindex/falkordbvector/base.py
> +            "SHOW INDEXES "
replace with
CALL db.indexes()

2024-09-19 07:44 UTC, AviAvni commented on llama-index-integrations/vector_stores/llama-index-vector-stores-falkordb/llamaindex/falkordbvector/base.py
> +            "YIELD name, type, entityType, properties, options "
see output in https://docs.falkordb.com/cypher/procedures.html

2024-09-19 07:44 UTC, AviAvni commented on llama-index-integrations/vector_stores/llama-index-vector-stores-falkordb/llamaindex/falkordbvector/base.py
> +            f"WITH n, vector.similarity.{self.distance_strategy}("
see https://docs.falkordb.com/cypher/indexing.html#vector-indexing how to use vector indexing

2024-09-24 07:25 UTC, AviAvni reviewed
it looks good now missing the docs and all the other files like in the other libs like pyproject.toml etc

2024-09-24 15:38 UTC, A5jadAli commented
@AviAvni please have a look at docs and if there's anything you think we need to change drop a comment, I'll fix it asap.

2024-09-24 16:37 UTC, AviAvni requested changes
One small change

2024-09-25 05:48 UTC, AviAvni approved these changes

2024-09-28 05:17 UTC, gkorland commented
@logan-markewich can you please review/merge?

2024-09-30 22:07 UTC, logan-markewich approved these changes

2024-10-04 19:25 UTC, logan-markewich commented
@gkorland @AviAvni I fixed a handful of issues, but the unit tests don't seem to work. Did you run them locally?

2024-10-04 19:39 UTC, A5jadAli commented
yes, they were working fine for me

On Sat, Oct 5, 2024 at 12:25 AM Logan ***@***.***> wrote:

> @gkorland <https://github.com/gkorland> @AviAvni
> <https://github.com/AviAvni> I fixed a handful of issues, but the unit
> tests don't seem to work. Did you run them locally?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/run-llama/llama_index/pull/16047#issuecomment-2394433887>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5MFIX7JLYITNO3DTJLIXGTZZ3TTDAVCNFSM6AAAAABOJYEEZCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJUGQZTGOBYG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-05 16:54 UTC, logan-markewich commented
@A5jadAli try running them, they don't actually work. Previously the mock db client wasn't being used (and the URL was also invalid) -- changed it slightly to use the mock client so that things are actually testable in CICD, but most tests fail (likely because things aren't mocked out entirely)

2024-10-05 17:13 UTC, A5jadAli commented
Ok, I'll check it out.

On Sat, Oct 5, 2024 at 9:54 PM Logan ***@***.***> wrote:

> @A5jadAli <https://github.com/A5jadAli> try running them, they don't
> actually work. Previously the mock db client wasn't being used (and the URL
> was also invalid) -- changed it slightly to use the mock client so that
> things are actually testable in CICD, but most tests fail (likely because
> things aren't mocked out entirely)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/run-llama/llama_index/pull/16047#issuecomment-2395116375>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5MFIX2MHGZ5ZPU4J754DTDZ2AKVFAVCNFSM6AAAAABOJYEEZCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJVGEYTMMZXGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-27 21:18 UTC, A5jadAli commented
I have updated the tests, can you check it now?

On Sat, Oct 5, 2024 at 10:12 PM Asjad Ali ***@***.***> wrote:

> Ok, I'll check it out.
>
> On Sat, Oct 5, 2024 at 9:54 PM Logan ***@***.***> wrote:
>
>> @A5jadAli <https://github.com/A5jadAli> try running them, they don't
>> actually work. Previously the mock db client wasn't being used (and the URL
>> was also invalid) -- changed it slightly to use the mock client so that
>> things are actually testable in CICD, but most tests fail (likely because
>> things aren't mocked out entirely)
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/run-llama/llama_index/pull/16047#issuecomment-2395116375>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/A5MFIX2MHGZ5ZPU4J754DTDZ2AKVFAVCNFSM6AAAAABOJYEEZCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGOJVGEYTMMZXGU>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2024-10-29 12:23 UTC, A5jadAli commented
@logan-markewich can you check and merge the changes now?

2024-11-11 15:37 UTC, gkorland approved these changes

2024-11-25 03:35 UTC, closed without merging