Raspawar/add vlm support
run-llama/llama_index pull request #16751
Opened 2024-10-30 11:59 UTC by raspawar

## Support for vision-language models, those that can accept images and text as input and produce text.

these are akin to https://platform.openai.com/docs/guides/vision with three notable differences -

- images can be passed with img tags in the regular text content
- images can be passed as NVCF asset ids
not all model endpoints support all features, e.g. server-side download of images not available with 
adept/fuyu-8b, google/deplot, microsoft/kosmos-2, google/paligemma; some models endpoints restrict image size; some models support one and only image; some models do not support gif or webp; kosmos-2 does not support streaming

cc: @sumitkbh @mattf @dglogo

2024-10-30 17:28 UTC, mattf requested changes
please address comments.

failing tests -
```
FAILED tests/test_multi_modal_nvidia.py::test_vlm_asset_id[invoke-content0-microsoft/phi-3-vision-128k-instruct] - TypeError: sequence item 0: expected str instance, function found
FAILED tests/test_multi_modal_nvidia.py::test_vlm_asset_id[stream-content0-microsoft/phi-3-vision-128k-instruct] - TypeError: sequence item 0: expected str instance, function found
```

2024-10-30 17:28 UTC, mattf commented on llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/llama_index/multi_modal_llms/nvidia/base.py
> +    default_headers: Optional[Dict[str, str]] = Field(
what's the use case for `default_headers`?

2024-10-30 17:28 UTC, mattf commented on llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/llama_index/multi_modal_llms/nvidia/base.py
> +    _completion_to_prompt: Callable = PrivateAttr()
how and where is `_completion_to_prompt` used?

2024-10-30 17:28 UTC, mattf commented on llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/llama_index/multi_modal_llms/nvidia/base.py
> +        raise NotImplementedError("This function is not yet implemented.")
please implement.

suggestion: rename _complete -> _chat, use generate_nvidia_multi_modal_chat_message + _chat in complete

2024-10-30 17:28 UTC, mattf commented on llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/llama_index/multi_modal_llms/nvidia/base.py
> +        raise NotImplementedError("This function is not yet implemented.")
please implement.

suggestion: rename _stream_complete -> _stream_chat, use generate_nvidia_multi_modal_chat_message + _stream_chat in stream_complete

2024-10-30 17:28 UTC, mattf commented on llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/llama_index/multi_modal_llms/nvidia/base.py
> +    # ===== Async Endpoints =====
implement or open issue to finish implementation

2024-11-05 12:16 UTC, mattf requested changes

2024-11-05 12:16 UTC, mattf commented on llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/llama_index/multi_modal_llms/nvidia/base.py
> +    default_headers: Optional[Dict[str, str]] = Field(
why give users control over headers used internally?

2024-11-05 12:16 UTC, mattf commented on llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/llama_index/multi_modal_llms/nvidia/base.py
> +        _client._custom_headers = {"User-Agent": "llama-index-multi-modal-llms-nvidia"}
it appears `_custom_headers` is not used. please move the user agent into NVIDIAClient's _get_headers.

2024-11-11 06:59 UTC, raspawar commented on llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/tests/data/nvidia-picasso-large.png
got it will do

2024-11-11 13:58 UTC, raspawar commented
@logan-markewich can u ptal. I donno why the coverage is considering the test cases also.

2024-11-12 08:50 UTC, raspawar commented on llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-nvidia/README.md
Done!

2024-11-14 02:09 UTC, logan-markewich approved these changes

2024-11-14 02:09 UTC, merged