Improve MyScale Hybrid Search and Add `DELETE` for MyScale vector store
run-llama/llama_index pull request #8159
Opened 2023-10-17 05:47 UTC by mpskex

# Description

This change is made by @suchme19.

-  add the delete func of myscale vectorstore  and update the corresponding document
-  adjust the pre search limit ratio about hybrid search to avoid excessively large pre search result

Fixes # (issue)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Added new unit/integration tests
- [X] Added new notebook (that tests end-to-end)
- [ ] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [ ] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I ran `make format; make lint` to appease the lint gods

2023-10-18 23:15 UTC, nerdai commented
Thanks @mpskex. I noticed that lint check has failed in our CI. Can you please run `make lint`?

2023-10-19 15:37 UTC, nerdai requested changes
Thanks for contributing to this @mpskex! 🔥 

Just some minor things.

2023-10-19 17:07 UTC, nerdai commented
@mpskex One other thing: can you please update the `CHANGELOG.md` with a new line of a few words describing this new feature add?

2023-10-20 07:48 UTC, mpskex commented on docs/examples/vector_stores/MyScaleIndexDemo.ipynb
> -   ],
Reverted

2023-10-20 07:48 UTC, mpskex commented on docs/examples/vector_stores/MyScaleIndexDemo.ipynb
> -   ],
Kept

2023-10-20 07:49 UTC, mpskex commented
> @mpskex One other thing: can you please update the `CHANGELOG.md` with a new line of a few words describing this new feature add?

Added into new features and bug fixes

2023-10-20 13:34 UTC, nerdai approved these changes
LGTM!!

Thank you.

2023-10-20 13:35 UTC, nerdai commented
Merging this now.

2023-10-20 13:35 UTC, merged