Allow init of stores_text variable for Pinecone vector store
run-llama/llama_index pull request #8633
Opened 2023-11-02 03:05 UTC by nishanthooda

# Description

This allows the the stores_text variable to be initialized with the PineconeVectorStore and used as the flag to determine whether text should be removed from metadata when storing node in Pinecone. 

This is useful for organizations who don't want plaintext document data stored in Pinecone. 

Fixes # (issue)

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] I stared at the code and made sure it makes sense

# Suggested Checklist:

- [x] I have performed a self-review of my own code
- [x] I ran `make format; make lint` to appease the lint gods

2023-11-02 05:42 UTC, Disiok requested changes
Would prefer to keep `stores_text` as a class attribute for consistency with base class.

Perhaps we can just add a separate override flag to achieve this behavior?

2023-11-02 13:48 UTC, nishanthooda commented
@Disiok makes sense - updated with a separate flag 👍

2023-11-02 21:28 UTC, nishanthooda commented
@Disiok anymore thoughts here?

2023-11-02 21:33 UTC, Disiok approved these changes
Sure!

2023-11-03 00:13 UTC, nishanthooda commented
@Disiok sorry about that - didn't lint and test the 2nd time around. Updated and CI should pass now!

2023-11-03 22:34 UTC, merged